#ifndef _SETTINGS_H_
#define _SETTINGS_H_


#define BB_DEBUG

#define PIN_WIRE_SDA 18
#define PIN_WIRE_SCL 19
#define PIN_HEAD_SERVO 3

#define RC_MIN_SIGNAL 1100u
#define RC_MID_SIGNAL 1500u
#define RC_MAX_SIGNAL 1900u

#define ACCEL_MAX 1.4

#define GYRO_FILTER_RC 0.1f
#define ACCEL_FILTER_RC 0.1f
#define ACCEL_CORRECTION_RC 1.0f

#define CALIBRATION_SAMPLES 10
#define CALIBRATION_INTERVAL 100

#define DEBUG_INTERVAL 500000

#define STABILIZE_UPDATE_INTERVAL 1000
#define STABILIZE_PRECISION 100
#define STABILIZE_OUTPUT_SCALE 100000

#define STABILIZE_KP 30
#define STABILIZE_KI 1
#define STABILIZE_KD 10


#endif